site_name: Motelandro
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  # - mkdocstrings: # Comentado temporalmente hasta que tengas los archivos
  #     handlers:
  #       python:
  #         paths: ["."]

nav:
  - Inicio: index.md
  # - Referencias: api.md
  # - Comandos: user-guide/commands.md
  # - Guia de inicio: getting-started.md
  # - Arquitectura: architecture.md
  # - Referencia: reference.md
  # - Persistencia: user-guide/persistence.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true